### ISSUE TITLE
Exception occurred in traits notification handler for object in "LithologiesClassesOverlayVisual3d.view_overlay"

### ISSUE THREAD

**Issue by jmp75** [jmp75/pyela#9]
Overlayed view: code works on the Perth Peel data, but on the Condamine this error occures. The DEM and point bore data does display, but not the volumes. The color coding of the bore also looks wrong. Repro with exploratory-lithology-analysis\case_studies\Condamine\Condamine_Facies.ipynb

**Comment by jmp75** [comment]
```text
Traceback (most recent call last):
  File "C:\Users\xxxyyy\AppData\Local\Continuum\anaconda3\envs\ELA3\lib\site-packages\tvtk\array_handler.py", line 698, in convert_array
    vtk_arr = getattr(vtk, vtk_typ)()
TypeError: this is an abstract class and cannot be instantiated

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\xxxyyy\AppData\Local\Continuum\anaconda3\envs\ELA3\lib\site-packages\traits\trait_notifiers.py", line 340, in __call__
    self.handler( *args )
  File "C:\Users\xxxyyy\AppData\Local\Continuum\anaconda3\envs\ELA3\lib\site-packages\mayavi\sources\array_source.py", line 251, in _scalar_data_changed
    img_data.point_data.scalars = np.ravel(np.transpose(data))
  File "tvtk_classes\data_set_attributes.py", line 269, in _set_scalars
    my_arg = deref_array([arg], [['vtkDataArray']])
  File "C:\Users\xxxyyy\AppData\Local\Continuum\anaconda3\envs\ELA3\lib\site-packages\tvtk\array_handler.py", line 814, in deref_array
    ret.append(convert_array(a, s))
  File "C:\Users\xxxyyy\AppData\Local\Continuum\anaconda3\envs\ELA3\lib\site-packages\tvtk\array_handler.py", line 700, in convert_array
    return array2vtk(arr)
  File "C:\Users\xxxyyy\AppData\Local\Continuum\anaconda3\envs\ELA3\lib\site-packages\tvtk\array_handler.py", line 319, in array2vtk
    vtk_typecode = get_vtk_array_type(z.dtype)
  File "C:\Users\xxxyyy\AppData\Local\Continuum\anaconda3\envs\ELA3\lib\site-packages\tvtk\array_handler.py", line 216, in get_vtk_array_type
    raise TypeError("Couldn't translate array's type to VTK")
TypeError: Couldn't translate array's type to VTK
Cannot contour: No scalars in input data!
```
